functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Должна быть возможность регистрации нового пользователя на сайте
  - Должна быть возможность авторизации на сайте уже зарегистрированному пользователю
  - У пользователя не должно быть возможности вносить какие-либо изменения на сайт (что-то удалять, добавлять новое и т.д)
  - Валюта, в которой отображается цена, должна меняться в зависимости от выбранного языка (страны)
  - Язык сайта должен автоматически определятся согласно ip-адресу пользователя
  - Пользователь должен иметь возможность просматривать историю своих заказов и отслеживать их статус
  - Корзина, данные учетной записи пользователя, история заказов должны быть недоступны для просмотра другим пользователям
  - Должна быть кнопка сброса установленных фильтров
